project:
  type: website

branches:
  - branch: "release-2605"
    output-dir: "2605"

website:
  title: ""
  favicon: "img/OSitSCfavicon.png"
  sidebar:
    style: "floating"
    width: 240px
    background: "white"
    fontsize: 35px
    search: true
    contents: 
      - index.qmd 
      - Schedule.qmd
      - Instructors.qmd
   
     

  navbar:
    background: "#111F36"
    logo: "img/OSitSCLogo2.png"
    right:
       - icon: github
         href: "https://github.com/SciLifeLab-Training/open-science"
         aria-label: GitHub


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

execute:
  freeze: auto

