project:
  type: website

branches:
  - branch: "release-2503"
    output-dir: "2503"

website:
  title: "Open Science in the Swedish context"
  favicon: "img/favicon-32x32.png"
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 35px
    search: true
    contents: 
      - index.qmd 
      - Schedule.qmd
      - Instructors.qmd
      - SS_GoodResearchPractice.qmd
      - SS_PreparatoryReading.qmd
      - 1_OpenScienceInSweden.qmd
      - 2_ProjectPlanningAndDesign.qmd
      - 3_ProjectSharingAndPublishing.qmd
      - 4_ResearcherEvaluation.qmd
      - SS_CitizenScienceAndScienceCommunication

     

  navbar:
    background: "#A7C947"
    logo: "img/SciLifeLab_Logotype_NEG.png"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

