project:
  type: website
  output-dir: "2505"

website:
  title: "Open Science in the Swedish context"
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 35px
    search: true
    contents: 
      - Index.qmd 
      - Schedule.qmd
      - Instructors.qmd
      - Session1.qmd
      - Session2.qmd
      - Session3.qmd
      - Session4.qmd
     

  navbar:
    background: "#A7C947"
    logo: "img/SciLifeLab_Logotype_NEG.png"
  favicon: "img/SciLifeLab_Logotype_NEG.png"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

