project:
  type: website

branches:
  - branch: "release-2505"
    output-dir: "2505"

website:
  title: "Open Science in the Swedish context"
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 35px
    search: true
    contents: 
      - index.qmd 
      - Schedule.qmd
      - Instructors.qmd
      - "<details><summary>Sessions</summary>
          <ul>
            <li><a href='Session1.qmd'>1. Open Science in Sweden</a></li>
            <li><a href='Session2.qmd'>2. Open Science in the project lifecycle - plan & design</a></li>
            <li><a href='Session3.qmd'>3. Open Science in the project lifecycle - collect & analyze</a></li>
            <li><a href='Session4.qmd'>4. Open Science in the project lifecycle - share & disseminate</a></li>
            <li><a href='Session5.qmd'>5. Open Science in the project lifecycle - access & reuse</a></li>
            <li><a href='Session6.qmd'>6. Open Science in the project lifecycle - evaluate</a></li>
            <li><a href='Session7.qmd'>7. Open Science in the project lifecycle - communicate & citizen science</a></li>
            <li><a href='Session8.qmd'>The National Guidelines for Open Science</a></li>
            <li><a href='Session9.qmd'>Open Science and intellectual property rights</a></li>
            <li><a href='Session10.qmd'>The future of Open Science</a></li>
          </ul>
        </details>"
      - Resources.qmd
     

  navbar:
    background: "#A7C947"
    logo: "img/SciLifeLab_Logotype_NEG.png"
  favicon: "img/SciLifeLab_Logotype_NEG.png"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

