---
title: "CARE Principles"
---

This session - held on **Tuesday 5 May 2026 at 11:00** - focuses on the CARE Principles for Indigenous Data Governance (Collective benefit, Authority to control, Responsibility, Ethics) and the guidance they provide regarding ethical and culturally responsive stewardship of Indigenous data. 

In the session we will discuss how adhering to these principles can differ from traditional approaches to data management, which aspects of the principles can have broader application than research involving indigenous data or knowledge, and practical strategies for integrating CARE principles into research projects.

If you have any questions about this module, please contact David Rayner <david.rayner@snd.se> or Stefan Ekman <stefan.ekman@snd.se>


## Preparations

<div class="lesson-overview">
### Read the following document

_Research Data Alliance International Indigenous Data Sovereignty Interest Group. (September 2019). [“CARE Principles for Indigenous Data Governance.”](https://www.rd-alliance.org/wp-content/uploads/2024/03/CARE20Principles20for20Indigenous20Data20Governance_OnePagers_FINAL20Sept2006202019.pdf). The Global Indigenous Data Alliance. _

We will begin the discussion with the question: _**which of the four principles attracted your attention the most, and why?**_

(Optional) Learn more about the status of the CARE principles in Sweden by reading the feature [CARE: Indigenous rights and open data](https://www.umu.se/en/feature/care-indigenous-rights-and-open-data/)

</div>

<!-- VERY IMPORTANT: blank line below -->

