---
title: "Monday 4 May 2026 – Foundations of Open Science"
format: html
---

### Quick Link: [Back to Course Overview](index.qmd)

## What is Open Science? {.session-overview}  
Instructor: [Ineke Luijten](Instructors.qmd#ineke-luijten)

This opening session provides an overview of the principles and practices that define Open Science. It introduces the historical development of Open Science and discusses its potential benefits and challenges for researchers and society.
    
<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTNzqJALu_fdTNMJL1t3mpxLYI1wI6PZxf2OdBrXgvX4JtlR4oZiZHueUeWTGIFtQ/pubembed?start=false&loop=false&delayms=3000" frameborder="0" width="700" height="420" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>   
  
<a href="https://docs.google.com/presentation/d/1GK9HhHQqISz05A3GFp8Nf0jK92pt2l0L/view" target="_blank">View in Google Slides</a> |  <a href="https://docs.google.com/presentation/d/1GK9HhHQqISz05A3GFp8Nf0jK92pt2l0L/copy" target="_blank">Make a Copy</a>   
    
----

## The State of Open Science in Sweden {.session-overview} 
Instructor: [Ineke Luijten](Instructors.qmd#ineke-luijten)

This session explores the current landscape of Open Science in Sweden and Europe, both institutionally and at the grassroots level. It presents the six key areas for the development of Open Science in Sweden and highlights major actors such as VR, SUHF, KB, and SND. The session also examines SUHF’s national roadmap and its ten recommendations, and discusses how Swedish higher education institutions are implementing these goals.
    
<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTmDgtAGOnHxQoLiBqKTCT9B6tnz4hAFYhzH6yZbWYZA1uaGRdKg5W9e0Y42_u6SXaWjpn8QzBtevG3/pubembed?start=false&loop=false&delayms=3000" frameborder="0" width="700" height="420" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>   

<a href="https://docs.google.com/presentation/d/1kMu3SN0TcENi06P7RPWCjzuFIubGelk4BSnV87QnEyg/view" target="_blank">View in Google Slides</a> |  <a href="https://docs.google.com/presentation/d/1kMu3SN0TcENi06P7RPWCjzuFIubGelk4BSnV87QnEyg/copy" target="_blank">Make a Copy</a>   

    
----

## The Ideology of Open Science {.session-overview} 
Instructor: [Stefan Ekman](Instructors.qmd#stefan-ekman)

This session examines the ideas shaping Open Science. We explore competing visions, from technology-focused models to approaches that emphasize process, inclusion, and collaboration. Topics include commercialization, unequal access to power and resources, and the tension between standardization and diverse ways of knowing. Rather than viewing Open Science simply as sharing results, the session invites participants to view Open Science as a path to a more inclusive, fair, and collaborative research system.   
  
For this session, participants may want to read:  

 _Fecher, Benedikt, and Sascha Friesike. 2014. ‘Open Science: One Term, Five Schools of Thought’. In Opening Science, edited by Sönke Bartling and Sascha Friesike. Springer International Publishing. [https://doi.org/10.1007/978-3-319-00026-8_2](https://doi.org/10.1007/978-3-319-00026-8_2)._  

### Abstract  
  
> Open Science is an umbrella term encompassing a multitude of assumptions about the future of knowledge creation and dissemination. Based on a literature review, this chapter aims at structuring the overall discourse by proposing five Open Science schools of thought: The infrastructure school (which is concerned with the technological architecture), the public school (which is concerned with the accessibility of knowledge creation), the measurement school (which is concerned with alternative impact measurement), the democratic school (which is concerned with access to knowledge) and the pragmatic school (which is concerned with collaborative research).
  
We will interrogate whether "open" in open science is an unqualified good, and ask whether particular interpretations of openness can in fact exclude particular researchers or be detrimental to some types of research.  
    
If you have any questions about this module, please contact Stefan Ekman  <stefan.ekman@snd.se>.
