---
title: "Tuesday 5 May 2026 – Planning and Sharing Research"
format: html
---

<br>

## Data Management Plans {.session-overview}  
Instructors: [Elin Kronander](Instructors.qmd#elin-kronander) and [Stephan Nylinder](Instructors.qmd#stephan-nylinder)

This session focuses on integrating Open Science practices early in the research process. Participants receive guidance on creating effective data management plans (DMPs), selecting open tools from the start, and understanding the key planning components of a DMP. The session also introduces related strategies such as preregistration and registered reports.

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTAuZsA62-ZAMV_utE4fWm1W2AS1blh8wQ5VUbz7R5-U2Avqn2OyJt-RLShgba5GdOUcrfJe_gHwkTx/pubembed?start=false&loop=false&delayms=3000" frameborder="0" width="700" height="420" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>   

<a href="https://docs.google.com/presentation/d/1_xoX5TCOn6Su_WhcVLcg5F1ahI-it-U_3F0nODUZ5es/view" target="_blank">View in Google Slides</a> |  <a href="https://docs.google.com/presentation/d/1_xoX5TCOn6Su_WhcVLcg5F1ahI-it-U_3F0nODUZ5es/copy" target="_blank">Make a Copy</a> 
   
----

## Parallel Session



### Intellectual Property {.session-overview}  
Instructor: [Camilla Pettersson](Instructors.qmd#camilla-pettersson)

Discussion centering on knowledge assets, intellectual property (IP) and intellectual property rights (IPR) in research and innovation. Covers e.g. the Swedish “teacher’s exemption”, managing your knowledge assets and IPR:s in collaborations, patents,  what can and cannot be protected, and the three patentability criteria: novelty, inventive step, and industrial application.

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRCut59jPO1BsTcoZQH8FWhmrERTQW2HflPbNN866kybHxrwVU6P94h6ScRPP2rJg/pubembed?start=false&loop=false&delayms=3000" frameborder="0" width="700" height="420" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>   

<a href="https://docs.google.com/presentation/d/1F-81vHZV-8JUXRYb03oAuCNM7QGxPXW0/view" target="_blank">View in Google Slides</a> |  <a href="https://docs.google.com/presentation/d/1F-81vHZV-8JUXRYb03oAuCNM7QGxPXW0/copy" target="_blank">Make a Copy</a>   

Read the [IP Policy of the University of Gothenburg (in English)](docs/University_of_Gothenburg_IP_policy_in_English.pdf). This is quite similar to most other Swedish universities IP Policies, and contains short descriptions of core topics for the session.  
This [short 6 minute video in Swedish](https://play.gu.se/media/0_9js65qob) explains basically what the IP Policy says.  
If you have any questions about this module, please contact Camilla Pettersson <camilla.pettersson@gu.se>


**OR**

### CARE Principles {.session-overview}  
Instructors: [David Rayner](Instructors.qmd#david-ryaner) and [Stefan Ekman](Instructors.qmd#stephan-ekman)

Introduction to the CARE Principles for Indigenous Data Governance (Collective benefit, Authority to control, Responsibility, Ethics).  The session will explain how these principles differ from traditional approaches to data management, focusing on the ethical, culturally responsive stewardship of Indigenous data. The session will discuss practical strategies for integrating CARE principles into research projects, promoting respect, transparency, and equitable outcomes for Indigenous communities.

----
 
## Repositories, Metadata, DOIs and Licensing {.session-overview}  
Instructors: [Elin Kronander](Instructors.qmd#elin-kronander) and [Stephan Nylinder](Instructors.qmd#stephan-nylinder)

This session focuses on how to maximize the visibility, accessibility, and reusability of research outputs after publication. It covers best practices for depositing outputs in open repositories, obtaining persistent identifiers, annotating using rich metadata, and applying appropriate open licenses. A practical exercise guides participants through uploading items to a repository (Zenodo), including adding metadata and selecting licenses.

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRZzZA2JdJDl2PvxaRd-skqjzlwtaCJKVe1du6sISvDx9zwTkKZqw6s74Phk_2dF5Td0q8gkTfHGFBe/pubembed?start=false&loop=false&delayms=3000" frameborder="0" width="700" height="420" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>   

<a href="https://docs.google.com/presentation/d/1mZ7LBqYMbyCalRt0xCBI04Lfa9MZ_pOBwP8fBIOQiLY/view" target="_blank">View in Google Slides</a> |  <a href="https://docs.google.com/presentation/d/1mZ7LBqYMbyCalRt0xCBI04Lfa9MZ_pOBwP8fBIOQiLY/copy" target="_blank">Make a Copy</a> 

Zenodo exercise instructions: [https://go.nbis.se/OS26-Zenodo](https://go.nbis.se/OS26-Zenodo)

----

## Open Educational Resources {.session-overview}  
Instructor: [Mattias von Feilitzen](Instructors.qmd#mattias-von-feilitzen)

This session introduces Open Educational Resources (OER) and their role in research and teaching. OER are digital materials that can be freely used, adapted, and shared, including study guides, slides, videos, podcasts, and full course packages. We will provide an overview of well-known platforms where educators can find and share open materials. 

The session will also address practical and legal considerations when reusing or adapting existing resources, including copyright, licensing choices, and publishing adapted materials. Participants will receive guidance on how to share their own teaching materials responsibly, how to select an appropriate license, and how to choose suitable platforms for dissemination.  

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRzON4rF_s1F2nfgeRB50oQzwkrVtvn_lyArhxJpiempTehv1EwdxLTV9oK0zSPOg/pubembed?start=false&loop=false&delayms=3000" frameborder="0" width="700" height="420" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>   

<a href="https://docs.google.com/presentation/d/1b0wJaQ8Nt4tC8t17-Ex708JDSfAABxUQ/view" target="_blank">View in Google Slides</a> |  <a href="https://docs.google.com/presentation/d/1b0wJaQ8Nt4tC8t17-Ex708JDSfAABxUQ/copy" target="_blank">Make a Copy</a>  


