---
title: "Thursday 7 May 2026 – Reuse and Communication"
format: html
---

<br>

## Reusing Research Data {.session-overview}  
Instructor: [David Rayner](Instructors.qmd#david-ryaner)

We begin with an introduction to open access to research data, focussing on different levels of openness for data that require protection

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRbvmQSQ7U92ZGxHwHoY3yH4rySsBeJEToKlJm1HPsI22__epXWWidtGKqOgV5k9w/pubembed?start=false&loop=false&delayms=3000" frameborder="0" width="700" height="420" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>  

<a href="https://docs.google.com/presentation/d/1FTJtFwhEl5_2RSTlFjAALei0rM110ntF/view" target="_blank">View in Google Slides</a> | <a href="docs/12_DavidRayner_OpenAccessToResearchData.pptx" download>  Download PowerPoint </a>

We continue with a practical session with both theoretical and practical guidance on reusing data from research data repositories. Among other things, it covers how to find, access, and evaluate datasets for reuse in new research. The session builds on an authentic research question that participants will address during the workshop! 

<a href="docs/12_DavidRayner_Data Reuse Lecture - Presentation Notes.pdf" target="_blank" download>Download presentation: Data Reuse Lecture with Notes (PDF)</a>  
<a href="docs/12_DavidRayner_DataReuseReanalysis.xlsx" target="_blank" download>Download spreadsheet: Example showing reanalysis of the data reuse data! (xlsx)</a>  

All material from this session - including PowerPoint slides - are available from <a href="https://doi.org/10.5281/zenodo.17294990">Zenodo</a>.

----
 
## Accessible archives with Citizen science {.session-overview}  
Instructor: [Karl-Magnus Johansson](Instructors.qmd#karl-magnus-johansson)

Citizen science and AI-based handwritten text recognition (HTR) are working together to make large volumes of historical handwritten documents accessible and searchable. By combining people’s ability to interpret difficult-to-read handwriting with AI’s speed for large-scale processing, access to archival material is being revolutionized. Karl-Magnus Johansson takes us on a tour of the project and describes the challenges and benefits of the citizen science approach. 

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vR6c4opcU77ECUCKZpqSymGNmzQWTKS5cjMvFgitpuF1m5EL2ujt7tStPL9_CG3wA/pubembed?start=false&loop=false&delayms=3000" frameborder="0" width="700" height="420" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>  

<a href="https://docs.google.com/presentation/d/1XLMg8JReeW3PX2M8yrAG-MCL0X_ZNPnm/view" target="_blank">View in Google Slides</a> |  <a href="docs/13_KarlMagnusJohansson_AccessibleArchives.pptx" download>
   Download PowerPoint </a> 

----

## Science Communication {.session-overview}  
Instructor: [Karin Westin Tikkanen](Instructors.qmd#karin-westin-tikkanen)

This session explores how researchers can broaden the impact and reach of their work through effective communication and public engagement. It provides an in-depth look at the seven principles of science communication and practical guidance on applying them. It includes strategies for summarizing research for policymakers and stakeholders to support evidence-based decision-making. 
During this session, participants will work in groups to develop an “elevator pitch” for their research or role!

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSCJ0n1mQJgzlqK7pPo2GLSrundknVya1dgi_NePIgUW9b0HijdOT3sfC9ghcfiNw/pubembed?start=false&loop=false&delayms=3000" frameborder="0" width="700" height="420" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe> 

<a href="https://docs.google.com/presentation/d/1PoCAqALrnRpeeyQNiHyUzLexjLWg4KkH/view" target="_blank">View in Google Slides</a> |  <a href="docs/14_KarinWestinTikkanen_ScienceCommunication.pptx" download>
   Download PowerPoint </a>
  
  
----
## Science Communication Grand Finale {.session-overview}  
Instructor: [Karin Westin Tikkanen](Instructors.qmd#karin-westin-tikkanen)

The course concludes with the Science Communication Grand Final, where participants deliver their elevator pitches to the class and participating teachers. 

Supplementary material: 
 
- <a href="docs/14_KarinWestinTikkanen_ElevatorPitchInstructions.pdf" download>"Elevator Pitch" instructions (PDF)</a>  

