---
title: "Intellectual Property"
---

### Tuesday 5 May 2026, 11:00 

Discussion centering on knowledge assets, intellectual property (IP) and intellectual property rights (IPR) in research and innovation. Covers e.g. the Swedish “teacher’s exemption”, managing your knowledge assets and IPR:s in collaborations, patents, what can and cannot be protected, and the three patentability criteria: novelty, inventive step, and industrial application.

## Camilla's Presentation

[Intellectual_Property_Open_Science_Camilla_Pettersson.pptx](docs/Intellectual_Property_Open_Science_Camilla_Pettersson.pptx)

## Preparations

Preparation is not necessary but will help you develop questions and ideas based on your own situation. 

If you have any questions about this module, please contact Camilla Pettersson <camilla.pettersson@gu.se>

<div class="lesson-overview">
## The IP Policy of the University of Gothenburg.

Read the [IP Policy of the University of Gothenburg (in English)](docs/University_of_Gothenburg_IP_policy_in_English.pdf). This is quite similar to most other Swedish universities IP Policies, and contains short descriptions of core topics for the session.

</div>

<div class="lesson-overview">
## (Optional) Watch a video explaining the IP policy.

This [short 6 minute video in Swedish](https://play.gu.se/media/0_9js65qob) explains basically what the IP Policy says.

</div>



<!-- VERY IMPORTANT: blank line below -->

