---
title: "Schedule"
---
<br>

::: {.callout-note}
Schedule is under development and subject to change. <br>
<span style="color:#E9967A;">Items highlighted in salmon indicate parallel sessions. Participants may choose one of the two options.</span> 
:::
 
<br/>

## **May 4**

| Time | Session |
|------|------|
| 13:00 - 14:00 | 1.1 What is Open Science? |
| 14:00 - 14:30 | 1.2 The state of Open Science in Sweden |
| 14:30 - 15:00 | Break |
| 15:00 - 16:30 | 1.3 The ideology of Open Science (group work)</span> |
: {tbl-colwidths="[25,75]"}  

<br/>

## **May 5**  

| Time | Session |
|------|------|
| 09:00 - 10:00 | 2.1 Plan & Design: Data Management Plans  |
| 10:00 - 10:30 | 2.2 Plan & Design: Reusing research data |
| 10:30 - 11:00 | Break|
| 11:00 - 12:00 | <span style="color:#E9967A;">2.3 Plan & Design: Intellectual property - OR - 2.4 Plan & Design: CARE principles</span> |
| 12:00 - 13:00 | Lunch |
| 13:00 - 14:30 | 3.1 Collect & Analyze: Citizen Science and stakeholder engagement |
| 14:30 - 15:00 | Break |
| 15:00 - 16:30 | <span style="color:#E9967A;">3.2 Collect & Analyze: Research with sensitive qualitative data - OR - 3.3 Collect & Analyze: Research with sensitive quantitative data</span> |
: {tbl-colwidths="[25,75]"}  

<br/>
     
## **May 6**    

| Time | Session |
|------|------|
| 09:00 - 10:30 | 4.1 Publish & Spread:  Publishing your results |
| 10:30 - 11:00 | Break|
| 11:00 - 12:00 | <span style="color:#E9967A;">4.2 Publish & Spread: Open Acces - code and models - OR - 4.3 Publish & Spread: Open Acces scholarly books </span> |
| 12:00 - 13:00 | Lunch |
| 13:00 - 13:30 | 5.1 Access & Reuse: Introduction to repositories, metadata, DOI & licensing   |
| 13:30 - 14:30 | 5.2 Access & Reuse: Repositories and metadata in practice (group work) |
| 14:30 - 15:00 | Break|
| 15:00 - 16:30 | 5.3 Access & Reuse: Sharing sensitive data  |
: {tbl-colwidths="[25,75]"}

<br/>

## **May 7**   

| Time | Session |
|------|------|
| 09:00 - 10:30 | 6.1 Communicate & Involve: Open Educational Resources |
| 10:30 - 11:00 | Break|
| 11:00 - 12:00 | 6.2 Communicate & Involve: How to use and create open educational resources (group work) |
| 12:00 - 13:00 | Lunch |
| 13:00 - 13:45 | 6.3 Communicate & Involve: Science Communication  |
| 13:45 - 14:30 | 6.4  Communicate & Involve: Science Communication  (group work) |
| 14:30 - 15:00 | Break|
| 15:00 - 16:30 | 6.5 Communicate & Involve: Grand finale   |
: {tbl-colwidths="[25,75]"}

<br/>

<br/>
