---
title: "Good Research Practice"
date: today
---
<br>
  
--- 

### **About**  
This module is primarily based on [Good Research Practice](https://www.vr.se/uppdrag/etik/god-forskningssed---ny-utgava.html) ('God forskningssed', VR, 2024) and the [European Code of Conduct for Research Integrity](https://allea.org/wp-content/uploads/2023/06/European-Code-of-Conduct-Revised-Edition-2023.pdf) (ALLEA, 2023). The information provided in this module is not exhaustive, but rather meant as an introduction to the topic. **Students are encouraged to further examine references to relevant laws and documents**. 

**Upon completion of this module, students will be able to:**   
- Demonstrate an understanding of ethical principles and legal frameworks governing research in Sweden  
- Execute every facet of an academic project according to Good Research Practice     
**Mode of study:** self-paced 
   
---   
  
### **Assignment**      
Please work through chapters 1-7 and answer the reflection questions in the Google form.

Chapter overview:   
[1. Introduction to Good Research Practice](SS_GRP1.qmd)  
[2. GRP in acquiring funding](SS_GRP2.qmd)  
[3. GRP in experimental research](SS_GRP3.qmd)  
[4. GRP in (inter)national collaboration](SS_GRP4.qmd)  
[5. GRP in publishing and reviewing](SS_GRP5.qmd)  
[6. Scientific misconduct](SS_GRP6.qmd)  
[7. GRP and Open Science](SS_GRP7.qmd)  


  
<span style="color: #A7C947;">**Total reading time: ~ 1h  <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Total reflection question time: ~ 1h ** </span>

---  

[Next →](SS_GRP1.qmd){.btn .btn-primary}
  
---  

